### ISSUE TITLE
No icon for KDE Plasma Wayland session

### ISSUE THREAD

**Issue by johnclark456** [gitneeraj/lightdm-webkit2-theme-reactive#22]
The icon works fine for the Plasma X11 session but just leaves an empty rectangle for my Wayland session.

**Comment by gitneeraj** [comment]
@johnclark456  Could you please share the screenshot of the issue?
Also it would be very helpful if you do the following and the share its output - 
1. Open terminal emulator and run command `lightdm-webkit2-greeter`. This opens up the DM in an separate instance.
2. Once above is opened, open context menu by right clicking anywhere on the screen and select `Inspect Element`. This opens up a window below in the same instance window
3. Select the `Console` tab and in the bottom you can type some commands. Type in `window.lightdm.sessions` and hit enter. This will spit out some data.
4. Below are the images I pasted for your reference
![kde-wayland-issue](https://user-images.githubusercontent.com/36226187/147749503-cb6576c8-1325-41c0-8269-75eafe0d9694.png)

**Comment by johnclark456** [comment]
I couldn't write-click as you showed but I hacked your index.html to get the info you are after:
`[{"name":"Plasma (Wayland)","key":"plasmawayland","comment":"Plasma by KDE"},
{"name":"Plasma (X11)","key":"plasma","comment":"Plasma by KDE"},
{"name":"Sway","key":"sway","comment":"An i3-compatible Wayland compositor"}]
`

**Comment by gitneeraj** [comment]
@johnclark456 released a fix for this in the version 0.4.8
Please make sure you re-install this theme. Let me know if you hit any other roadblocks.
Thank you!

**Comment by johnclark456** [comment]
Thanks, works now, looks great btw, I'll keep an eye out for any issues. Great work!
