### ISSUE TITLE
Password

### ISSUE THREAD

**Issue by zaggash** [gitneeraj/lightdm-webkit2-theme-reactive#30]
I think this  

https://github.com/gitneeraj/lightdm-webkit2-theme-reactive/commit/49bca3a5e6e91552373be3fafe1ed1ab05ee853c
  
Deserve a new release for security fix, don't you?

**Comment by gitneeraj** [comment]
Hey @zaggash `0.4.9` is the new release for the security fix #29 

Same has been updated in Arch AUR as well
